# Generated by Django 3.1.1 on 2021-01-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='problem',
            fields=[
                ('problem_id', models.AutoField(primary_key=True, serialize=False)),
                ('problem_name', models.TextField()),
                ('problem_statement', models.TextField()),
                ('problem_tags', models.TextField()),
                ('problem_io', models.TextField()),
                ('problem_con', models.TextField()),
            ],
        ),
    ]
