# Generated by Django 3.1.1 on 2021-03-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='problemfeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_feedback', models.TextField()),
                ('email', models.TextField()),
                ('problem_id', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='problem',
            name='problem_con',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='problem_io',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='problem_test',
        ),
        migrations.AddField(
            model_name='problem',
            name='problem_example',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='problem_input',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='problem_noofsubmission',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='problem_output',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='problem_samplecase',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='problem_score',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_tags',
            field=models.TextField(null=True),
        ),
    ]
