# Generated by Django 3.1.1 on 2021-03-06 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_auto_20210305_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='problem_noofsubmission',
            field=models.TextField(default=0, null=True),
        ),
    ]
