# Generated by Django 3.1.1 on 2021-03-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userrecommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_id', models.IntegerField()),
                ('email', models.TextField()),
                ('status', models.TextField(null=True)),
                ('lineofcode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='userrecommend2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_id', models.IntegerField()),
                ('email', models.TextField()),
                ('nooftry', models.IntegerField(default=0)),
                ('itime', models.DateTimeField(null=True)),
                ('ftime', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='userrecommend3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
                ('topicid', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='userrecommend4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
                ('loginstarttime', models.DateTimeField(null=True)),
                ('loginendtime', models.DateTimeField(null=True)),
            ],
        ),
    ]
