# Generated by Django 3.1.1 on 2021-03-07 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userrecommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_id', models.IntegerField()),
                ('email', models.TextField()),
                ('status', models.JSONField()),
                ('timetaken', models.IntegerField()),
                ('lineofcode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='userrecommend2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_id', models.IntegerField()),
                ('email', models.TextField()),
                ('nooftry', models.IntegerField()),
                ('rating', models.TextField()),
                ('difficulty', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='userrecommend3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
                ('timespent', models.IntegerField()),
                ('tagsserach', models.TextField()),
                ('tsc', models.IntegerField()),
                ('tsp', models.IntegerField()),
            ],
        ),
    ]
