# Generated by Django 3.1.1 on 2021-03-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecommend4',
            name='loginstarttime',
            field=models.DateTimeField(),
        ),
    ]
