# Generated by Django 3.1.1 on 2021-03-08 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0002_auto_20210307_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecommend',
            name='status',
            field=models.TextField(),
        ),
    ]
