# Generated by Django 3.1.1 on 2021-03-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0003_auto_20210308_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='userrecommend6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_id', models.IntegerField()),
                ('email', models.TextField()),
                ('status', models.TextField()),
                ('lineofcode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='userrecommend7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_id', models.IntegerField()),
                ('email', models.TextField()),
                ('nooftry', models.IntegerField(default=0)),
                ('itime', models.DateTimeField(null=True)),
                ('ftime', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='userrecommend8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
                ('topicid', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='userrecommend9',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
                ('loginstarttime', models.DateTimeField()),
                ('loginendtime', models.DateTimeField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='userrecommend',
        ),
        migrations.DeleteModel(
            name='userrecommend2',
        ),
        migrations.DeleteModel(
            name='userrecommend3',
        ),
        migrations.DeleteModel(
            name='userrecommend4',
        ),
    ]
