# Generated by Django 3.1.1 on 2021-01-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contest',
            fields=[
                ('contestid', models.AutoField(primary_key=True, serialize=False)),
                ('duration', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('timestamp', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='contestproblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contestid', models.CharField(max_length=200)),
                ('problemid', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='contestuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contestid', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=1000)),
            ],
        ),
    ]
