# Generated by Django 3.1.1 on 2021-01-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_auto_20210124_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='id',
            field=models.AutoField(auto_created=True, default='1', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contest',
            name='contestid',
            field=models.CharField(max_length=200),
        ),
    ]
