# Generated by Django 3.1.1 on 2021-01-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_auto_20210124_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='id',
        ),
        migrations.AlterField(
            model_name='contest',
            name='contestid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
