# Generated by Django 3.1.1 on 2021-01-24 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0004_auto_20210124_1529'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contest',
        ),
    ]
