# Generated by Django 3.1.1 on 2021-01-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0005_delete_contest'),
    ]

    operations = [
        migrations.CreateModel(
            name='contest',
            fields=[
                ('contestid', models.AutoField(primary_key=True, serialize=False)),
                ('duration', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('timestamp', models.CharField(max_length=1000)),
            ],
        ),
    ]
