# Generated by Django 3.1.1 on 2021-01-24 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0007_auto_20210124_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest2',
            name='title',
        ),
    ]
