# Generated by Django 3.1.1 on 2021-01-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0008_remove_contest2_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest2',
            name='title',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
    ]
