# Generated by Django 3.1.1 on 2021-01-24 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0009_contest2_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contest2',
        ),
    ]
