# Generated by Django 3.1.1 on 2021-01-24 10:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0010_delete_contest2'),
    ]

    operations = [
        migrations.CreateModel(
            name='contest2',
            fields=[
                ('contestid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duration', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('timestamp', models.CharField(max_length=1000)),
            ],
        ),
    ]
