# Generated by Django 3.1.1 on 2021-01-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0011_contest2'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestuser',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
