# Generated by Django 3.1.1 on 2021-02-04 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0012_contestuser_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest2',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
