# Generated by Django 3.1.1 on 2021-03-05 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0013_auto_20210204_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestuser',
            name='problemid',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
