# Generated by Django 3.1.1 on 2021-01-22 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='id',
            field=models.AutoField(auto_created=True, default='1', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='response',
            name='discussionId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discussion.discussion'),
        ),
    ]
