# Generated by Django 3.1.1 on 2021-01-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='email',
            field=models.CharField(max_length=120, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='response',
            name='discussionId',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='response',
            name='email',
            field=models.CharField(max_length=120, verbose_name='email'),
        ),
    ]
