# Generated by Django 3.1.1 on 2021-01-22 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0002_auto_20210122_2112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='discussionId',
            new_name='responseid',
        ),
    ]
