# Generated by Django 3.1.1 on 2021-01-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='isadmin',
            field=models.CharField(default='False', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.IntegerField(default=500, null=True),
        ),
    ]
