# Generated by Django 3.1.1 on 2021-03-05 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submissions',
            old_name='Username',
            new_name='user_id',
        ),
    ]
