# Generated by Django 3.1.1 on 2021-03-05 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20210305_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.user', to_field='email'),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.user', to_field='email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.TextField(unique=True),
        ),
    ]
