# Generated by Django 3.1.1 on 2021-03-24 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20210305_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recommended',
            field=models.TextField(null=True),
        ),
    ]
