# Generated by Django 3.1.1 on 2021-01-22 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='topic',
            fields=[
                ('topic_id', models.AutoField(primary_key=True, serialize=False)),
                ('topic_module', models.TextField()),
                ('topic_name', models.TextField()),
                ('topic_vlink', models.TextField()),
                ('topic_content', models.TextField()),
            ],
        ),
    ]
