# Generated by Django 3.1.1 on 2021-01-22 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.TextField()),
                ('type_article', models.TextField(db_column='type')),
            ],
            options={
                'db_table': 'medications',
            },
        ),
    ]
